Fix imgcat and teach it a --height option

diff --git a/utilities/imgcat b/utilities/imgcat
--- a/utilities/imgcat
+++ b/utilities/imgcat
@@ -1,22 +1,46 @@
 #!/bin/bash
-# Output images to the terminal using iTerm2
+# Custom version of imgcat using escape codes documented at https://iterm2.com/documentation-images.html
 
 set -e
 set -u
 set -o pipefail
 
-if [ $# -eq 0 ]; then
-    echo "Usage: imgcat { file | url }..."
-    exit 1
-fi
+help() {
+  echo "usage: $0 [--height <height>] { file | url }..."
+  echo
+  echo "Outputs images to the terminal using iTerm2 escape codes."
+  echo
+}
+
+usage_error() {
+  echo "error: $*"
+  echo
+  help
+  exit 2
+} >&2
+
+height=auto
+
+while (( $# > 0 )); do
+    case "$1" in
+        --height) shift; height="$1";;
+        -'?' | --help) help; exit;;
+        --) shift; break;;
+        -*) usage_error "unknown option $1" "Use '--' to separate arguments from options";;
+        *) break;;
+    esac
+    shift
+done
+
+[ $# -gt 0 ] || usage_error "no files or URLs provided"
 
 function show_image() {
-    printf '\033]1337;File=name='`echo -n "$1" | base64`";"
-    wc -c "$1" | awk '{printf "size=%d",$1}'
-    printf ";inline=1"
-    printf ":"
-    base64 < "$1"
-    printf '\a\n'
+    printf '\033]1337;File=name=%s;height=%s;size=%d;inline=1:%s\a\n' \
+        "$(printf %s "$1" | base64)" \
+        "${height}" \
+        "$(cat "$1" | wc -c)" \
+        "$(base64 <"$1")" \
+        ;
 }
 
 for img in "$@"; do
